[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.0 ; For structured data exchange
    ESP32Async/ESPAsyncWebServer @ 3.6.0
    ESP32Async/AsyncTCP @ 3.4.10
    adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.2
    adafruit/Adafruit BusIO @ ^1.16.1
    SPI ; SPI is built into the ESP32 core, but explicitly referencing it ensures clean builds

